version: "3"
services: 
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: dalongrong/dotnetcoreaspnet-demo:alpine
    ports: 
    - "80:80"
  app-build:
    build: 
      context: ./
      dockerfile: Dockerfile-multistage
    image: dalongrong/dotnetcoreaspnet-demo2:alpine
    ports: 
    - "8080:80"
  app-benchmark:
    build: 
      context: ./
      dockerfile: Dockerfile-benchmark
    image: dalongrong/dotnetcorebenchmark-demo:alpine